// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 15.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfApp1
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SvgQuaderTemplate : SvgQuaderTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<!-- https://msdn.microsoft.com/de-de/library/ee844259.aspx -->
<svg  xmlns=""http://www.w3.org/2000/svg""
      xmlns:xlink=""http://www.w3.org/1999/xlink"" height=""100%"" width=""100%"" viewBox=""0 0 3000 1800"">
	<g transform=""scale(-1,1) translate(-3000)"" visibility=""visible"">
		<rect id=""plane1"" x=""0"" y=""0"" height=""1800"" width=""3000"" style=""stroke:#000000; fill: #ffffff""/>
		<g id=""s_1_k"">
			<path d=""M 0 ");
            
            #line 12 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(0.25*Width + Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 13 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 13 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 14 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 14 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 15 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write(" 0 \r\n\t\t\t\tL ");
            
            #line 16 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write(" 0 \r\n\t\t\t\tL ");
            
            #line 17 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height + (0.25*Width)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(0.25*Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 18 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height + (0.25*Width)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 18 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(0.75*Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 19 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 19 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 20 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2* Level + 2*Height+ 2*Depth));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tL ");
            
            #line 21 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(3*Depth + 2*Height + 2*Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + 0.25*Width));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tL ");
            
            #line 22 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(3*Depth + 2*Height + 2*Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 22 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + 0.75*Width));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tL ");
            
            #line 23 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth + 2*Height + 2*Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 23 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tL ");
            
            #line 24 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Height + Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 24 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tL ");
            
            #line 25 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height + (0.25*Width)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 25 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + 1.25*Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 26 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height + (0.25*Width)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 26 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + 1.75*Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 27 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + 2*Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 28 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 28 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + 2*Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 29 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + Depth));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\tL ");
            
            #line 30 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 30 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + Depth));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tL 0 ");
            
            #line 31 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(0.75 *Width + Depth));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\tz\" fill=\"#ffffff\" stroke=\"blue\" stroke-width=\"0.1mm\" />\r\n\t\t\t<line x1=\"");
            
            #line 33 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 33 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 33 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 33 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" stroke-width=\"0.1mm\"/>\r\n\t\t\t<line x1=\"");
            
            #line 34 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 34 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 34 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 34 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"grey\" stroke-width=\"0.1mm\"/>\r\n\t\t\t<line x1=\"");
            
            #line 35 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("\" y1=\"0\" x2=\"");
            
            #line 35 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 35 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Width + 2*Depth));
            
            #line default
            #line hidden
            this.Write(" \" stroke=\"red\" stroke-width=\"0.1mm\"/>\t\t\t\t\t\r\n\t\t\t<line x1=\"");
            
            #line 36 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 36 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 36 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 36 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" stroke-width=\"0.1mm\"/>\t\r\n\t\t\t<line x1=\"");
            
            #line 37 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth +  Level + 2*Height));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 37 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 37 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth +  Level + 2*Height));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 37 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"grey\" stroke-width=\"0.1mm\"/>\t\t\t\t\t\r\n\t\t\t<line x1=\"");
            
            #line 38 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth + 2* Level + 2*Height));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 38 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 38 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Depth + 2* Level + 2*Height));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 38 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" stroke-width=\"0.1mm\"/>\r\n\t\t\t<line x1=\"");
            
            #line 39 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 39 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 39 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 39 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" stroke-width=\"0.1mm\"/>\r\n\t\t\t<line x1=\"");
            
            #line 40 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 40 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 40 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Level + Height));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 40 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgQuaderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Depth + Width));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" stroke-width=\"0.1mm\"/>\r\n\t\t</g>\r\n\t</g>\r\n</svg>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class SvgQuaderTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
