// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 15.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfApp1
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SvgZylinderTemplate : SvgZylinderTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<!-- https://msdn.microsoft.com/de-de/library/ee844259.aspx -->
<svg  xmlns=""http://www.w3.org/2000/svg""
      xmlns:xlink=""http://www.w3.org/1999/xlink"" height=""100%"" width=""100%"" viewBox=""0 0 3000 1800"">
	<g transform=""scale(-1,1) translate(-3000)"" visibility=""visible"">
		<rect id=""plane1"" x=""0"" y=""0"" height=""1800"" width=""3000"" style=""stroke:#000000; fill: #ffffff""/>
		<path d=""
		M ");
            
            #line 12 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 12 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\ta ");
            
            #line 13 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 13 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(",0,0,1,-");
            
            #line 13 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius*0.5));
            
            #line default
            #line hidden
            this.Write(",-");
            
            #line 13 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl 0, -");
            
            #line 14 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Height));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl 15, -15\r\n\t\tl ");
            
            #line 16 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Radius -30));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t    l 15, 15\r\n\t\tl 0, ");
            
            #line 18 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Height));
            
            #line default
            #line hidden
            this.Write("\r\n\t\ta ");
            
            #line 19 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 19 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(",0,0,1,-");
            
            #line 19 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius*0.5));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 19 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl ");
            
            #line 20 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2* Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\ta  ");
            
            #line 21 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 21 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(",0,0,1,-");
            
            #line 21 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius*0.5));
            
            #line default
            #line hidden
            this.Write(",-");
            
            #line 21 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl 0, -");
            
            #line 22 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Height));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl 15, -15\r\n\t\tl ");
            
            #line 24 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2*Radius -30));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\tl 15, 15\r\n\t\tl 0, ");
            
            #line 26 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Height));
            
            #line default
            #line hidden
            this.Write("\r\n\t\ta ");
            
            #line 27 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 27 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius));
            
            #line default
            #line hidden
            this.Write(",0,0,1,-");
            
            #line 27 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius*0.5));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 27 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl ");
            
            #line 28 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\tl 15, 15\r\n\t\tl 0, ");
            
            #line 30 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Height));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tl -15, 15\r\n\t\tl -");
            
            #line 32 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2* Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\tl -15, 15\r\n\t\tl -");
            
            #line 34 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius - 30));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\tl -15, -15\r\n\t\tl -");
            
            #line 36 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(2* Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\tl -15, 15\r\n\t\tl -");
            
            #line 38 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Radius - 30));
            
            #line default
            #line hidden
            this.Write(", 0\r\n\t\tl -15, -15\r\n\t\tZ\" stroke=\"blue\" id=\"e6_path\" style=\"fill: none; stroke-widt" +
                    "h: 2px;\"/>\r\n\t<line id=\"e7_line\" x1=\"");
            
            #line 41 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 41 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 41 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 41 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e8_line\" x1=\"" +
                    "");
            
            #line 42 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX - Radius*0.5));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 42 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 42 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius*1.5));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 42 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e9_line\" x1=\"" +
                    "");
            
            #line 43 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX - Radius*0.5));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 43 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5 - Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 43 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius*1.5));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 43 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5 - Height));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e10_line\" x1=" +
                    "\"");
            
            #line 44 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 44 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 44 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2*Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 44 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e11_line\" x1=" +
                    "\"");
            
            #line 45 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX - Radius * 0.5 + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 45 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 45 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX - Radius * 0.5 + 2 * Math.PI * Radius / 3 + 2 * Radius));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 45 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e12_line\" x1=" +
                    "\"");
            
            #line 46 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX - Radius * 0.5 + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 46 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5 - Radius *2));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 46 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX - Radius * 0.5 + 2 * Math.PI * Radius / 3 + 2 * Radius));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 46 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY - Math.Sqrt(3) * Radius * 0.5 - Radius *2));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e1_line\" x1=\"" +
                    "");
            
            #line 47 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 47 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 47 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 47 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e2_line\" x1=\"" +
                    "");
            
            #line 48 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 48 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 48 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2*Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 48 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e3_line\" x1=\"" +
                    "");
            
            #line 49 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2*Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 49 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 49 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2*Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 49 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e4_line\" x1=\"" +
                    "");
            
            #line 50 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 50 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 50 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius + 2 * Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 50 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e6_line\" x1=\"" +
                    "");
            
            #line 51 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 51 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 51 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 51 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e13_line\" x1=" +
                    "\"");
            
            #line 52 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius + Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 52 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 52 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + Radius + Math.PI * Radius / 3));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 52 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e14_line\" x1=" +
                    "\"");
            
            #line 53 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2 * Radius + Math.PI * Radius));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 53 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 53 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2 * Radius + Math.PI * Radius));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 53 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t<line id=\"e15_line\" x1=" +
                    "\"");
            
            #line 54 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2 * Radius + 4* Math.PI * Radius /3));
            
            #line default
            #line hidden
            this.Write("\" y1=\"");
            
            #line 54 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY + Height));
            
            #line default
            #line hidden
            this.Write("\" x2=\"");
            
            #line 54 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startX + 2 * Radius + 4* Math.PI * Radius /3));
            
            #line default
            #line hidden
            this.Write("\" y2=\"");
            
            #line 54 "c:\Users\Linda\documents\visual studio 2017\Projects\WpfApp1\WpfApp1\SvgZylinderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(startY));
            
            #line default
            #line hidden
            this.Write("\" stroke=\"red\" style=\"stroke-width: 2px; fill: none;\"/>\r\n\t</g>\r\n</svg>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class SvgZylinderTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
